set encoding=utf-8
scriptencoding utf-8

runtime bundle/vim-pathogen/autoload/pathogen.vim

let g:pathogen_disabled = []

if v:version < '800'
  call add(g:pathogen_disabled, 'ale')
else
  call add(g:pathogen_disabled, 'syntastic')
endif

execute pathogen#infect()

syntax on
filetype plugin indent on

let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

set nu
set modelines=0

set path+=**

set background=dark
colorscheme luinnar
let g:monokai_term_italic = 1
let g:monokai_gui_italic = 1

set ignorecase smartcase
set grepprg=grep\ -IrsnH

set showcmd ruler laststatus=2

set splitright

set history=500
set hidden
set nobackup
set noundofile
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc

set listchars=trail:.,tab:>-,extends:>,precedes:<,nbsp:¬
set list

set backspace=indent,eol,start
set showmatch
set wildmode=full
set wildmenu
set complete-=i

set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set foldlevelstart=2

set iskeyword+=-

let NERDTreeIgnore=['\~$', '.o$', 'bower_components', 'node_modules', '__pycache__']

inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

set scrolloff=999
set sidescrolloff=0

set sidescroll=1

let g:ruby_heredoc_syntax_filetypes = {
  \ "sql" : {
  \   "start" : "SQL",
  \},
  \ "xml" : {
  \   "start" : "XML",
  \},
\}

if v:version < '800'
  let g:syntastic_ruby_checkers = ['rubocop']
  set statusline+=%#warningmsg#
  set statusline+=%{SyntasticStatuslineFlag()}
  set statusline+=%*

  let g:syntastic_always_populate_loc_list = 1
  let g:syntastic_auto_loc_list = 1
  let g:syntastic_check_on_open = 1
  let g:syntastic_check_on_wq = 0
endif
